package TrabalhoLPOO;

public enum Paises {
    //Foram ignorados países com território inferior à 10.000 km quadrados.
    AFG("AFG", "Afeganistão"),
    ZAF("ZAF", "África do Sul"),
    ALB("ALB", "Albânia"),
    DEU("DEU", "Alemanha"),
    AGO("AGO", "Angola"),
    ATA("ATA", "Antártida"),
    SAU("SAU", "Arábia Saudita"),
    DZA("DZA", "Argélia"),
    ARG("ARG", "Argentina"),
    ARM("ARM", "Armênia"),
    AUS("AUS", "Austrália"),
    AUT("AUT", "Áustria"),
    AZE("AZE", "Azerbaijão"),
    BHS("BHS", "Bahamas"),
    BGD("BGD", "Bangladesh"),
    BRB("BRB", "Barbados"),
    BLR("BLR", "Belarus"),
    BEL("BEL", "Bélgica"),
    BLZ("BLZ", "Belize"),
    BEN("BEN", "Benin"),
    BOL("BOL", "Bolívia"),
    BIH("BIH", "Bósnia-Herzegóvina"),
    BWA("BWA", "Botsuana"),
    BRA("BRA", "Brasil"),
    BGR("BGR", "Bulgária"),
    BFA("BFA", "Burkina Fasso"),
    BDI("BDI", "Burundi"),
    BTN("BTN", "Butão"),
    CMR("CMR", "Camarões"),
    KHM("KHM", "Camboja"),
    CAN("CAN", "Canadá"),
    KAZ("KAZ", "Cazaquistão"),
    TCD("TCD", "Chade"),
    CHL("CHL", "Chile"),
    CHN("CHN", "China"),
    COL("COL", "Colômbia"),
    COG("COG", "Congo"),
    PRK("PRK", "Coréia do Norte"),
    KOR("KOR", "Coréia do Sul"),
    CIV("CIV", "Costa do Marfim"),
    CRI("CRI", "Costa Rica"),
    HRV("HRV", "Croácia (Hrvatska)"),
    CUB("CUB", "Cuba"),
    DNK("DNK", "Dinamarca"),
    DJI("DJI", "Djibouti"),
    EGY("EGY", "Egito"),
    SLV("SLV", "El Salvador"),
    ARE("ARE", "Emirados Árabes Unidos"),
    ECU("ECU", "Equador"),
    SVK("SVK", "Eslováquia"),
    SVN("SVN", "Eslovênia"),
    ESP("ESP", "Espanha"),
    USA("USA", "Estados Unidos"),
    EST("EST", "Estônia"),
    ETH("ETH", "Etiópia"),
    FJI("FJI", "Fiji"),
    PHL("PHL", "Filipinas"),
    FIN("FIN", "Finlândia"),
    FRA("FRA", "França"),
    GAB("GAB", "Gabão"),
    GMB("GMB", "Gâmbia"),
    GHA("GHA", "Gana"),
    GEO("GEO", "Geórgia"),
    GBR("GBR", "Grã-Bretanha (Reino Unido, UK)"),
    GRC("GRC", "Grécia"),
    GRL("GRL", "Groelândia"),
    GTM("GTM", "Guatemala"),
    GUY("GUY", "Guiana"),
    GUF("GUF", "Guiana Francesa"),
    GIN("GIN", "Guiné"),
    GNQ("GNQ", "Guiné Equatorial"),
    GNB("GNB", "Guiné-Bissau"),
    HTI("HTI", "Haiti"),
    NLD("NLD", "Holanda"),
    HND("HND", "Honduras"),
    HUN("HUN", "Hungria"),
    YEM("YEM", "Iêmen"),
    IND("IND", "índia"),
    IDN("IDN", "Indonésia"),
    IRN("IRN", "Irã"),
    IRQ("IRQ", "Iraque"),
    IRL("IRL", "Irlanda"),
    ISL("ISL", "Islândia"),
    ISR("ISR", "Israel"),
    ITA("ITA", "Itália"),
    JAM("JAM", "Jamaica"),
    JPN("JPN", "Japão"),
    JEY("JEY", "Jersey"),
    JOR("JOR", "Jordânia"),
    KEN("KEN", "Kênia"),
    KWT("KWT", "Kuait"),
    LAO("LAO", "Laos"),
    LVA("LVA", "Látvia"),
    LSO("LSO", "Lesoto"),
    LBN("LBN", "Líbano"),
    LBR("LBR", "Libéria"),
    LBY("LBY", "Líbia"),
    LTU("LTU", "Lituânia"),
    MKD("MKD", "Macedônia (República Yugoslava)"),
    MDG("MDG", "Madagascar"),
    MYS("MYS", "Malásia"),
    MWI("MWI", "Malaui"),
    MLI("MLI", "Mali"),
    MAR("MAR", "Marrocos"),
    MRT("MRT", "Mauritânia"),
    MEX("MEX", "México"),
    FSM("FSM", "Micronésia"),
    MOZ("MOZ", "Moçambique"),
    MDA("MDA", "Moldova"),
    MNG("MNG", "Mongólia"),
    MNE("MNE", "Montenegro"),
    MMR("MMR", "Myanmar"),
    NAM("NAM", "Namíbia"),
    NPL("NPL", "Nepal"),
    NIC("NIC", "Nicarágua"),
    NER("NER", "Níger"),
    NGA("NGA", "Nigéria"),
    NOR("NOR", "Noruega"),
    NCL("NCL", "Nova Caledônia"),
    NZL("NZL", "Nova Zelândia"),
    OMN("OMN", "Omã"),
    PAN("PAN", "Panamá"),
    PNG("PNG", "Papua-Nova Guiné"),
    PAK("PAK", "Paquistão"),
    PRY("PRY", "Paraguai"),
    PER("PER", "Peru"),
    POL("POL", "Polônia"),
    PRT("PRT", "Portugal"),
    QAT("QAT", "Qatar"),
    KGZ("KGZ", "Quirguistão"),
    CAF("CAF", "República Centro-Africana"),
    COD("COD", "República Democrática do Congo"),
    DOM("DOM", "República Dominicana"),
    CZE("CZE", "República Tcheca"),
    ROM("ROM", "Romênia"),
    RWA("RWA", "Ruanda"),
    RUS("RUS", "Rússia (antiga URSS) - Federação Russa"),
    ESH("ESH", "Saara Ocidental"),
    SEN("SEN", "Senegal"),
    SLE("SLE", "Serra Leoa"),
    SRB("SRB", "Sérvia"),
    SYR("SYR", "Síria"),
    SOM("SOM", "Somália"),
    LKA("LKA", "Sri Lanka"),
    SWZ("SWZ", "Suazilândia"),
    SDN("SDN", "Sudão"),
    SWE("SWE", "Suécia"),
    CHE("CHE", "Suíça"),
    SUR("SUR", "Suriname"),
    TJK("TJK", "Tadjiquistão"),
    THA("THA", "Tailândia"),
    TWN("TWN", "Taiwan"),
    TZA("TZA", "Tanzânia"),
    TMP("TMP", "Timor Leste"),
    TGO("TGO", "Togo"),
    TUN("TUN", "Tunísia"),
    TKM("TKM", "Turcomenistão"),
    TUR("TUR", "Turquia"),
    UKR("UKR", "Ucrânia"),
    UGA("UGA", "Uganda"),
    URY("URY", "Uruguai"),
    UZB("UZB", "Uzbequistão"),
    VUT("VUT", "Vanuatu"),
    VEN("VEN", "Venezuela"),
    VNM("VNM", "Vietnã"),
    ZMB("ZMB", "Zâmbia"),
    ZWE("ZWE", "Zimbábue");

    private String nome;
    private String Sigla;

    Paises(String nSigla, String nNome) {
        this.Sigla = nSigla;
        this.nome = nNome;
    }

    public String getNome() {
        return nome;
    }

    public String getSigla() {
        return Sigla;
    }
}
